app:
  bootstrap:
    # Password of the administrator created on a fresh install. Override it in every real deployment.
    admin-password: ${ADMIN_PASSWORD:admin123}

spring:
  application:
    name: TheArchivist

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  ai:
    vectorstore:
      qdrant:
        collection-name: archivist-lore
        initialize-schema: false
